apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetnxt
  namespace: davis-kube
  labels:
    app: dotnetnxt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetnxt
  template:
    metadata:
      labels:
        app: dotnetnxt
    spec:
      containers:
        - name: dotnetnxt
          image: prdctmntc.azurecr.io/davisimage:#{Release.Artifacts.builds.BuildId}#
         
          imagePullPolicy: Always

          ports:
            - containerPort: 7050
            - containerPort: 7050
      imagePullSecrets:
        - name: prdctmntc
--- 

---
apiVersion: v1
kind: Service
metadata:
  name: dotnetnxt
spec:
  type: LoadBalancer
  ports:
    - name: http5
      port: 7050
    - name: http51
      port: 7050
  selector:
    app: dotnetnxt
